In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
!gdown 1u2Q5cS0qCt0OEdtCzBcn4UfBKQAFMl30

Downloading...
From: https://drive.google.com/uc?id=1u2Q5cS0qCt0OEdtCzBcn4UfBKQAFMl30
To: c:\Python Course\Session\TELECOM-CHURN-PREDICTION\notebooks\Telco-Customer-Churn.csv

  0%|          | 0.00/978k [00:00<?, ?B/s]
 54%|█████▎    | 524k/978k [00:00<00:00, 971kB/s]
100%|██████████| 978k/978k [00:00<00:00, 1.46MB/s]
100%|██████████| 978k/978k [00:00<00:00, 1.35MB/s]

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('../DATA/Telco-Customer-Churn.csv')

# **EDA**

In [11]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [6]:
df.tail(8)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7035,8456-QDAVC,Male,0,No,No,19,Yes,No,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Bank transfer (automatic),78.70,1495.1,No
7036,7750-EYXWZ,Female,0,No,No,12,No,No phone service,DSL,No,...,Yes,Yes,Yes,Yes,One year,No,Electronic check,60.65,743.3,No
7037,2569-WGERO,Female,0,No,No,72,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Bank transfer (automatic),21.15,1419.4,No
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [12]:
df.sample(4)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
2297,3870-MQAMG,Female,0,Yes,No,54,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,One year,No,Electronic check,110.35,5893.15,Yes
2025,1488-PBLJN,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),116.85,8477.7,No
4101,9780-FKVVF,Male,0,No,No,6,Yes,No,DSL,Yes,...,No,No,No,Yes,Month-to-month,Yes,Bank transfer (automatic),59.15,336.7,No
555,5791-KAJFD,Female,0,Yes,Yes,56,Yes,Yes,DSL,Yes,...,Yes,No,No,Yes,One year,Yes,Bank transfer (automatic),68.75,3808,No

In [10]:
df.shape

(7043, 21)

In [13]:
df.index

RangeIndex(start=0, stop=7043, step=1)

In [14]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [16]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [17]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [20]:
df.isna().sum().sort_values(ascending=False)

TotalCharges        11
gender               0
SeniorCitizen        0
Partner              0
customerID           0
Dependents           0
tenure               0
MultipleLines        0
PhoneService         0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
InternetService      0
TechSupport          0
StreamingTV          0
Contract             0
StreamingMovies      0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
Churn                0
dtype: int64

In [ ]:
# Check for missing values
df.isna().sum().sort_values(ascending=False)

In [ ]:
df.isna()

In [ ]:
df.isna().any(axis=0)

In [ ]:
df[df.isna().any(axis=1)]

In [ ]:
# Fill missing TotalCharges with tenure * MonthlyCharges

df.loc[df['TotalCharges'].isna(), 'TotalCharges'] = df['tenure'] * df['MonthlyCharges']

In [ ]:
# Check again for missing values
df.isna().sum()

In [ ]:
df.info()

In [ ]:
df.loc[5:9, 'TotalCharges']

In [ ]:
df['gender'].value_counts()

In [ ]:
df.head(1)

In [ ]:
# Convert categorical variables to numeric using mapping
df['Partner'] = df['Partner'].map({ 'No' : 0, 'Yes': 1})
df['Dependents'] = df['Dependents'].map({ 'No' : 0, 'Yes': 1})
df['PhoneService'] = df['PhoneService'].map({ 'No' : 0, 'Yes': 1})
df['MultipleLines'] = df['MultipleLines'].map({ 'No' : 0, 'Yes': 1, 'No phone service': 2})
df['InternetService'] = df['InternetService'].map({ 'No' : 0, 'DSL': 1, 'Fiber optic': 2})
df['OnlineSecurity'] = df['OnlineSecurity'].map({ 'No' : 0, 'Yes': 1, 'No internet service': 2})
df['OnlineBackup'] = df['OnlineBackup'].map({ 'No' : 0, 'Yes': 1, 'No internet service': 2})
df['DeviceProtection'] = df['DeviceProtection'].map({ 'No' : 0, 'Yes': 1, 'No internet service': 2})
df['TechSupport'] = df['TechSupport'].map({ 'No' : 0, 'Yes': 1, 'No internet service': 2})
df['StreamingTV'] = df['StreamingTV'].map({ 'No' : 0, 'Yes': 1, 'No internet service': 2})
df['StreamingMovies'] = df['StreamingMovies'].map({ 'No' : 0, 'Yes': 1, 'No internet service': 2})
df['Contract'] = df['Contract'].map({ 'Month-to-month' : 0, 'One year': 1, 'Two year': 2})
df['PaperlessBilling'] = df['PaperlessBilling'].map({ 'No' : 0, 'Yes': 1})
df['PaymentMethod'] = df['PaymentMethod'].map({ 'Electronic check' : 0, 'Mailed check': 1, 'Bank transfer (automatic)': 2, 'Credit card (automatic)': 3})
df['Churn'] = df['Churn'].map({ 'No' : 0, 'Yes': 1})

In [ ]:
df.head(1)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
# Get list of categorical columns (excluding customerID)
categorical_col_list = df.select_dtypes(include='object').columns.tolist()[1:]

In [ ]:
for i in categorical_col_list:
  print(f'Value counts for {i}: \n {df[i].value_counts()}')
  print('=============================')

In [ ]:
df.describe()

In [ ]:
df.corr(numeric_only=True)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# get list of numeric columns
numeric_col_list = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

In [ ]:
numeric_col_list

In [ ]:
for i in numeric_col_list:
  plt.figure()
  sns.boxplot(df[i])
  plt.title(f'Distribution of {i}')
  plt.show()

In [ ]:
for i in numeric_col_list:
  plt.figure()
  sns.histplot(df[i], kde=True)
  plt.title(f'Distribution of {i}')
  plt.show()

In [ ]:
for i in categorical_col_list:
  plt.figure()
  sns.countplot(df[i])
  plt.title(f'Distribution of {i}')
  plt.show()

# **Feature Engineering**

In [ ]:
df

In [ ]:
df.info()

In [ ]:
X = df.iloc[:, 1:-1]

In [ ]:
X

In [ ]:
y = df.iloc[:, -1]

In [ ]:
y

In [ ]:
y = y.map({'Yes': 1, 'No': 0})

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
import joblib

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [ ]:
numeric_col_list = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols_list = X.select_dtypes(include='object').columns.tolist()

print(numeric_col_list)
print(categorical_col_list)

In [ ]:
numeric_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ]
)

In [ ]:
categorical_transformer = Pipeline(
    steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]
)

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_col_list),
        ('cat', categorical_transformer, categorical_cols_list)
    ]
)

In [ ]:
preprocessor

# **Modeling**

In [ ]:
log_reg_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', LogisticRegression())
    ]
)

In [ ]:
log_reg_pipeline.fit(X_train, y_train)

# **Model Evaluation**

In [ ]:
y_pred_log_reg = log_reg_pipeline.predict(X_test)

In [ ]:
cm=confusion_matrix(y_test, y_pred_log_reg)
print(classification_report(y_test, y_pred_log_reg))
print(cm)
print("Accuracy:", f"{accuracy_score(y_test, y_pred_log_reg) * 100:.2f} %")

sns.heatmap(cm, annot=True, fmt='d')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

In [ ]:
rf_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier())
    ]
)

In [ ]:
rf_param_grid = {
    'classifier__n_estimators': [i for i in range(100, 1001 , 100)],
    'classifier__max_depth': [None, 5,10, 15, 20],
    'classifier__min_samples_split': [2, 5, 7,10],    
    'classifier__min_samples_leaf': [1, 2, 5,10]   
}

In [ ]:
grid_search_rf = GridSearchCV(
    estimator=rf_pipeline, 
    param_grid=rf_param_grid, 
    scoring='f1',
    cv=5, n_jobs=-1, verbose=1)

In [ ]:

grid_search_rf.fit(X_train, y_train)

In [ ]:
print("Best Hyperparameters for Random Forest:", grid_search_rf.best_params_)

In [ ]:
best_rf = grid_search_rf.best_estimator_

y_pred_rf= best_rf.predict(X_test)

In [ ]:
cm=confusion_matrix(y_test, y_pred_rf)
print(classification_report(y_test, y_pred_rf))
print(cm)
print("Accuracy:", f"{accuracy_score(y_test, y_pred_rf) * 100:.2f} %")

sns.heatmap(cm, annot=True, fmt='d')
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

In [ ]:
xgboost_pipeline = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', xgb.XGBClassifier(use_label_encoder=False, eval_metric='logloss'))
    ]
)

In [ ]:
xgboost_param_grid = {
    'classifier__n_estimators': [i for i in range(100, 1001 , 100)],
    'classifier__max_depth': [None, 5,10, 15, 20],
    'classifier__learning_rate': [0.01, 0.1, 0.2, 0.3   ],  
    'classifier__subsample': [0.6, 0.8, 1.0],
    'classifier__colsample_bytree': [0.6, 0.8, 1.0],
    'classifier__gamma': [0, 0.1, 0.2, 0.3],
}

In [ ]:
xgboost_grid_search = GridSearchCV(
    estimator=xgboost_pipeline, 
    param_grid=xgboost_param_grid, 
    scoring='f1',
    cv=5, n_jobs=-1, verbose=1)

In [ ]:
!pip install joblib

In [ ]:
import joblib

In [ ]:
joblib.dump(log_reg_pipeline, 'log_reg_pipeline.joblib')
print   ('Logistic Regression pipeline saved successfully!')